// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ScoreHub.Infrastructure.Persistence;

#nullable disable

namespace ScoreHub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ScoreHubDbContext))]
    [Migration("20260504120000_AddActivityMaterialUrls")]
    partial class AddActivityMaterialUrls
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Snapshot intentionally omitted for manually-applied migration
        }
    }
}
