// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ScoreHub.Infrastructure.Persistence;

#nullable disable

namespace ScoreHub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ScoreHubDbContext))]
    [Migration("20260617000000_AddActivityTemplateSortOrder")]
    partial class AddActivityTemplateSortOrder
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
