// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScoreHub.Infrastructure.Persistence;

#nullable disable

namespace ScoreHub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ScoreHubDbContext))]
    partial class ScoreHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("ScoreHub.Domain.Entities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LectureBasePoints")
                        .HasColumnType("TEXT");

                    b.Property<int>("MiniTestDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MiniTestMaxBonus")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("MiniTestOpenedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MiniTestPublished")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreLectureVideoUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.ActivityAssistant", b =>
                {
                    b.Property<Guid>("ActivityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssistantId")
                        .HasColumnType("TEXT");

                    b.HasKey("ActivityId", "AssistantId");

                    b.HasIndex("AssistantId");

                    b.ToTable("ActivityAssistants");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalGradingTableJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KtMultiplierMapJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.HomeworkSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Result01")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ReviewStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReviewerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TimeCoefficient")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("TaskItemId");

                    b.ToTable("HomeworkSubmissions");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.HomeworkSubmissionMember", b =>
                {
                    b.Property<Guid>("HomeworkSubmissionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("HomeworkSubmissionId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("HomeworkSubmissionMembers");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.MiniTestAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AnsweredAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BonusAwarded")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SelectedOptionIndex")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("StudentId");

                    b.HasIndex("ActivityId", "StudentId", "QuestionId")
                        .IsUnique();

                    b.ToTable("MiniTestAnswers");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.MiniTestQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CorrectOptionIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.ToTable("MiniTestQuestions");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.StudentActivityScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HomeworkPoints")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("KtMultiplier")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LecturePoints")
                        .HasColumnType("TEXT");

                    b.Property<int>("ModuleNumber")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ModuleScore")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("CourseId", "StudentId", "ModuleNumber")
                        .IsUnique();

                    b.ToTable("StudentActivityScores");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.TaskAssistant", b =>
                {
                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssistantId")
                        .HasColumnType("TEXT");

                    b.HasKey("TaskItemId", "AssistantId");

                    b.HasIndex("AssistantId");

                    b.ToTable("TaskAssistants");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Points")
                        .HasColumnType("TEXT");

                    b.Property<string>("Statement")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TaskSetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TaskSetId");

                    b.ToTable("TaskItems");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.TaskSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Published")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.ToTable("TaskSets");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.TaskSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DefenderCoefficient")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DefenderUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ReadyAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Result01")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReviewerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DefenderUserId");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TaskItemId");

                    b.HasIndex("TeamId");

                    b.HasIndex("ActivityId", "TaskItemId", "TeamId", "StudentId");

                    b.ToTable("TaskSubmissions");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.TeamAssistant", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssistantId")
                        .HasColumnType("TEXT");

                    b.HasKey("TeamId", "AssistantId");

                    b.HasIndex("AssistantId");

                    b.ToTable("TeamAssistants");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.TeamGroupScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BasePoints")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GroupCoefficient")
                        .HasColumnType("TEXT");

                    b.Property<int>("TasksAccepted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TasksTotal")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("TeamId", "ActivityId")
                        .IsUnique();

                    b.ToTable("TeamGroupScores");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.TeamHelpRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamHelpRequests");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAbsent")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("TeamId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.TeamSwapLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InitiatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StudentAId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StudentBId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TeamAId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TeamBId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InitiatedByUserId");

                    b.HasIndex("StudentAId");

                    b.HasIndex("StudentBId");

                    b.ToTable("TeamSwapLogs");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.Activity", b =>
                {
                    b.HasOne("ScoreHub.Domain.Entities.Module", "Module")
                        .WithMany("Activities")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.ActivityAssistant", b =>
                {
                    b.HasOne("ScoreHub.Domain.Entities.Activity", "Activity")
                        .WithMany("ActiveAssistants")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScoreHub.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AssistantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.HomeworkSubmission", b =>
                {
                    b.HasOne("ScoreHub.Domain.Entities.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScoreHub.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ScoreHub.Domain.Entities.TaskItem", "TaskItem")
                        .WithMany()
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.HomeworkSubmissionMember", b =>
                {
                    b.HasOne("ScoreHub.Domain.Entities.HomeworkSubmission", "HomeworkSubmission")
                        .WithMany("Members")
                        .HasForeignKey("HomeworkSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScoreHub.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HomeworkSubmission");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.MiniTestAnswer", b =>
                {
                    b.HasOne("ScoreHub.Domain.Entities.MiniTestQuestion", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScoreHub.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.MiniTestQuestion", b =>
                {
                    b.HasOne("ScoreHub.Domain.Entities.Activity", "Activity")
                        .WithMany("MiniTestQuestions")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.Module", b =>
                {
                    b.HasOne("ScoreHub.Domain.Entities.Course", "Course")
                        .WithMany("Modules")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.Notification", b =>
                {
                    b.HasOne("ScoreHub.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.StudentActivityScore", b =>
                {
                    b.HasOne("ScoreHub.Domain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScoreHub.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.TaskAssistant", b =>
                {
                    b.HasOne("ScoreHub.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AssistantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScoreHub.Domain.Entities.TaskItem", "TaskItem")
                        .WithMany("Assistants")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("ScoreHub.Domain.Entities.TaskSet", "TaskSet")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskSet");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.TaskSet", b =>
                {
                    b.HasOne("ScoreHub.Domain.Entities.Activity", "Activity")
                        .WithMany("TaskSets")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.TaskSubmission", b =>
                {
                    b.HasOne("ScoreHub.Domain.Entities.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScoreHub.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("DefenderUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ScoreHub.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ScoreHub.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ScoreHub.Domain.Entities.TaskItem", "TaskItem")
                        .WithMany()
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScoreHub.Domain.Entities.Team", "Team")
                        .WithMany("Submissions")
                        .HasForeignKey("TeamId");

                    b.Navigation("Activity");

                    b.Navigation("TaskItem");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.Team", b =>
                {
                    b.HasOne("ScoreHub.Domain.Entities.Activity", "Activity")
                        .WithMany("Teams")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.TeamAssistant", b =>
                {
                    b.HasOne("ScoreHub.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AssistantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScoreHub.Domain.Entities.Team", "Team")
                        .WithMany("Assistants")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.TeamGroupScore", b =>
                {
                    b.HasOne("ScoreHub.Domain.Entities.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScoreHub.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.TeamHelpRequest", b =>
                {
                    b.HasOne("ScoreHub.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScoreHub.Domain.Entities.Team", "Team")
                        .WithMany("HelpRequests")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.TeamMember", b =>
                {
                    b.HasOne("ScoreHub.Domain.Entities.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScoreHub.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.TeamSwapLog", b =>
                {
                    b.HasOne("ScoreHub.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("InitiatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScoreHub.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("StudentAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScoreHub.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("StudentBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.Activity", b =>
                {
                    b.Navigation("ActiveAssistants");

                    b.Navigation("MiniTestQuestions");

                    b.Navigation("TaskSets");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.Course", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.HomeworkSubmission", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.MiniTestQuestion", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.Module", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.TaskItem", b =>
                {
                    b.Navigation("Assistants");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.TaskSet", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("ScoreHub.Domain.Entities.Team", b =>
                {
                    b.Navigation("Assistants");

                    b.Navigation("HelpRequests");

                    b.Navigation("Members");

                    b.Navigation("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
